
name: Sandboxbeta-OM-Server 

on:
  workflow_dispatch:
    branches:
    - main
    paths:
      - ".github/workflows/testing connectivity.yml"


permissions:
  id-token: write
  contents: read

jobs:
  sync-cft:
    runs-on: ubuntu-latest
    steps:
    - name: multiple command
      uses: appleboy/ssh-action@v0.1.6
      with:
        host: ${{ secrets.HOST_OM }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY_OM }}
        port: ${{ secrets.PORT }}
        script: |
          whoami
          ls -al      
  
